name: gonramp_apollo_tools
owner: yating-l
remote_repository_url: https://github.com/Yating-L/suite_gonramp_apollo.git
categories: 
  - Visualization
description: A suite of tools for managing a (local) Apollo server
type: unrestricted
exclude:
  - tool_test_output.html
  - tool_test_output.json
