categories: [Visualization]
description: A tool to upload jbrowsehub to Apollo instance
name: jbrowsehubtoapollo
owner: yating-l
remote_repository_url: https://github.com/Yating-L/jbrowsehub-to-apollo.git
exclude:
  - tool_test_output.html
  - tool_test_output.json
